### ISSUE TITLE
Не работает отправка сообщений и не создаются комнаты

### ISSUE THREAD

**Issue by sdfsdhgjkbmnmxc** [f-person/nane_client#1]
См. видео: https://youtu.be/q3-nwFSbSiw

**Comment by f-person** [comment]
Комнаты создаются, когда отправляется сообщение. Всё это по вебсокетам. Ещё раз посмотрел код. Сообщения, по идее, должны были отправляться. На iOS тестировать не было возможности. Предпологаю, что данная проблема может как-то зависеть от платформы.

**Comment by f-person** [comment]
У меня тоже только что что-то подобное случилось. При потере соединения вебсокеты подключаются не сразу, а через несколько секунд. Возможно, соединение было потеряно во время, когда пытались отправить сообщение. Сейчас попробую исправить.

**Comment by f-person** [comment]
Проблема так же может быть связана с тем, что использовался класс `IOWebSocketChannel` вместо кросс-платформенного `WebSocketChannel`. Поменял это в fe42baf. Посмотрите, пожалуйста, ещё раз.

**Comment by sdfsdhgjkbmnmxc** [comment]
Со свежей версией (6ca12e7d05b8efd532d366690dffb1468d89b7b2) всё так же: пишешь-пишешь сообщение, а оно уходит в небытие.

**Comment by f-person** [comment]
К сожалению, не могу протестрировать на iOS устройстве. Можете попробовать на Android? [Тут](https://github.com/f-person/nane_client/releases/download/v1.1/app-release.apk) есть готовый APK.

**Comment by sdfsdhgjkbmnmxc** [comment]
На Android то же самое, просто скрины не так удобно снимать.

**Comment by f-person** [comment]
Странно, не пойму из-за чего не работают вебокеты. Можете показать вывод команды `flutter doctor -v`?

**Comment by sdfsdhgjkbmnmxc** [comment]
^C[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-RU)
    • Flutter version 2.0.3 at /Users/smee/flutter
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

⣽smee20:~ smee$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-RU)
    • Flutter version 2.0.3 at /Users/smee/flutter
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/smee/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128

**Comment by f-person** [comment]
А в консоль выводятся какие-либо ошибки, когда запускаете? Можете показать что происходит в консоли при запуске?

**Comment by sdfsdhgjkbmnmxc** [comment]
Предлагаю считать, что это продкшен-сборка, поставленная на телефон, и никаких других способов отладки, кроме добавленных в приложение автором, нет...

**Comment by f-person** [comment]
А, APK пробовали, окей.

**Comment by f-person** [comment]
Добавил обработку ошибок и логику для переподключения при ошибке.

[Новый APK](https://github.com/f-person/nane_client/releases/download/v1.3/app-release.apk)

**Comment by sdfsdhgjkbmnmxc** [comment]
Теперь ещё хуже: вылетает, когда начинаешь печатать в поле ввода сообщения.

**Comment by pauliemayhew** [comment]
Uploading 64034525599__9B2AD18B-E122-45F4-AB04-80FB6F5C4F12.MOV…

**Comment by pauliemayhew** [comment]
![Uploading D8709820-BF4B-446D-B568-BC6980D2FC5D.jpeg…]()

**Comment by pauliemayhew** [comment]
![photo_2021-04-17 12 48 39](https://user-images.githubusercontent.com/71446521/115108861-5f15f380-9f7b-11eb-954d-7a92c594d6ad.jpeg)

**Comment by pauliemayhew** [comment]
Баги, стоит приложение свернуть, то оно перестаёт реагировать, но отвисает. 
Не создаются новые темы,
не видно отправленных сообщений, внутри сообщений тоже не отображаются письма,
старых сообщений не видно

**Comment by pauliemayhew** [comment]
Когда пишешь большой текст ( вставкой ) приложуха тоже вылетает

**Comment by f-person** [comment]
А, понятно, забыл добавить кое-что. Сейчас уже при ошибке будет предложено отправить мне на почту. [Новый APK](https://github.com/f-person/nane_client/releases/download/v1.4/app-release.apk)

**Comment by sdfsdhgjkbmnmxc** [comment]
Теперь приложение вообще ни на что не реагирует. Просто вижу список комнат.

**Comment by f-person** [comment]
Были проблемы в логике переподключения, исправил в 144b9a1. Так же добавил возможность загружать комнаты, если произошла какая-то ошибка (интернета не было, например). [Новая сборка](https://github.com/f-person/nane_client/releases/download/v1.5/app-release.apk).

**Comment by sdfsdhgjkbmnmxc** [comment]
Теперь пишет, что нет соединения. История грузится, nane.tada.team с того же телефона свежие сообщения отображает.
<img width="592" alt="Screenshot 2021-04-21 at 14 57 06" src="https://user-images.githubusercontent.com/149195/115549978-fba90000-a2b1-11eb-8b41-d26d3ea66c90.png">

**Comment by f-person** [comment]
Это значит, что нет соединения по вебсокетам. Не пойму почему у вас не соединяется. Может брандмауэр блокирует? Вот видео, где протестировано на настоящем устройстве (Xiaomi Redmi Note 8): https://youtu.be/jy6bfyLd9O4, тут всё работает.

**Comment by sdfsdhgjkbmnmxc** [comment]
> Может брандмауэр блокирует?

Неа. Всё такое выключено.
